cat > dns-unlocker.sh << 'EOF'
#!/bin/bash
# DNS解锁脚本 - 简化版

# 确保输出是彩色的，即使通过管道或重定向
export TERM=xterm-256color

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# 检查是否为非交互模式
if [ ! -t 0 ]; then
  # 如果是通过管道执行，则将自己保存为临时文件并提供执行指令
  echo -e "${YELLOW}检测到非交互模式，正在准备脚本...${NC}"
  SCRIPT_PATH="/tmp/dns-unlocker-$(date +%s).sh"
  cat > "$SCRIPT_PATH" << 'INNEREOF'
#!/bin/bash
# DNS解锁脚本 - 简化版

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# 检查root权限
if [ "$(id -u)" != "0" ]; then
   echo -e "${RED}错误: 需要root权限${NC}" 1>&2
   echo -e "${YELLOW}请使用 sudo bash $0 运行此脚本${NC}"
   exit 1
fi

# 安装必要软件
echo -e "${BLUE}正在检查并安装必要软件...${NC}"
apt-get update
apt-get install -y dnsmasq jq

# 配置dnsmasq
setup_dnsmasq() {
  echo -e "${BLUE}配置基本dnsmasq设置...${NC}"
  cat > /etc/dnsmasq.conf << EOFCONF
# 基础配置
cache-size=1024
no-resolv
server=8.8.8.8
server=8.8.4.4
listen-address=127.0.0.1
conf-dir=/etc/dnsmasq.d/,*.conf
EOFCONF

  # 创建目录
  mkdir -p /etc/dnsmasq.d/
  echo -e "${GREEN}dnsmasq基础配置完成${NC}"
}

# 配置Netflix
setup_netflix() {
  echo -e "${CYAN}===== 解锁Netflix =====${NC}"
  read -p "输入用于解锁Netflix的IP: " ip
  if [ -z "$ip" ]; then
    echo -e "${RED}错误: IP地址不能为空${NC}"
    return
  fi
  
  cat > /etc/dnsmasq.d/netflix.conf << EOFSTREAM
# Netflix
address=/netflix.com/$ip
address=/nflxext.com/$ip
address=/nflximg.com/$ip
address=/nflximg.net/$ip
address=/nflxvideo.net/$ip
address=/nflxso.net/$ip
address=/netflix.net/$ip
EOFSTREAM
  echo -e "${GREEN}Netflix解锁已配置${NC}"
}

# 配置Disney+
setup_disney() {
  echo -e "${CYAN}===== 解锁Disney+ =====${NC}"
  read -p "输入用于解锁Disney+的IP: " ip
  if [ -z "$ip" ]; then
    echo -e "${RED}错误: IP地址不能为空${NC}"
    return
  fi
  
  cat > /etc/dnsmasq.d/disney.conf << EOFSTREAM
# Disney+
address=/disney.com/$ip
address=/disney-plus.net/$ip
address=/dssott.com/$ip
address=/disneyplus.com/$ip
address=/bamgrid.com/$ip
address=/disney-portal.my.onetrust.com/$ip
address=/disneystreaming.com/$ip
address=/disney.demdex.net/$ip
address=/disney.my.sentry.io/$ip
address=/cdn.registerdisney.go.com/$ip
address=/global.edge.bamgrid.com/$ip
address=/dssott.com.akamaized.net/$ip
address=/d9.flashtalking.com/$ip
address=/cdn.cdn.unid.go.com/$ip
address=/cws.conviva.com/$ip
EOFSTREAM
  echo -e "${GREEN}Disney+解锁已配置${NC}"
}

# 配置TikTok
setup_tiktok() {
  echo -e "${CYAN}===== 解锁TikTok =====${NC}"
  read -p "输入用于解锁TikTok的IP: " ip
  if [ -z "$ip" ]; then
    echo -e "${RED}错误: IP地址不能为空${NC}"
    return
  fi
  
  cat > /etc/dnsmasq.d/tiktok.conf << EOFSTREAM
# TikTok
address=/tiktok.com/$ip
address=/tiktokv.com/$ip
address=/tiktokcdn.com/$ip
address=/tiktokcdn-us.com/$ip
address=/tik-tokapi.com/$ip
address=/muscdn.com/$ip
EOFSTREAM
  echo -e "${GREEN}TikTok解锁已配置${NC}"
}

# 配置AI服务
setup_ai() {
  echo -e "${CYAN}===== 解锁AI服务 =====${NC}"
  read -p "输入用于解锁AI服务(OpenAI/Claude/Gemini)的IP: " ip
  if [ -z "$ip" ]; then
    echo -e "${RED}错误: IP地址不能为空${NC}"
    return
  fi
  
  cat > /etc/dnsmasq.d/ai.conf << EOFAI
# OpenAI
address=/openai.com/$ip
address=/ai.com/$ip
address=/chat.openai.com/$ip
address=/api.openai.com/$ip
address=/platform.openai.com/$ip

# Claude
address=/anthropic.com/$ip
address=/claude.ai/$ip
address=/api.anthropic.com/$ip

# Gemini
address=/gemini.google.com/$ip
address=/bard.google.com/$ip
address=/generativelanguage.googleapis.com/$ip
EOFAI
  echo -e "${GREEN}AI服务解锁已配置${NC}"
}

# 添加自定义域名
setup_custom() {
  echo -e "${CYAN}===== 添加自定义域名解锁 =====${NC}"
  read -p "输入要解锁的自定义域名: " domain
  if [ -z "$domain" ]; then
    echo -e "${RED}错误: 域名不能为空${NC}"
    return
  fi
  
  read -p "输入用于解锁 $domain 的IP: " ip
  if [ -z "$ip" ]; then
    echo -e "${RED}错误: IP地址不能为空${NC}"
    return
  fi
  
  # 处理域名，去掉可能的http://或https://前缀
  domain=$(echo $domain | sed -e 's|^https\?://||')
  # 移除末尾可能的斜杠
  domain=${domain%/}
  
  cat > "/etc/dnsmasq.d/custom_${domain//./\_}.conf" << EOFCUSTOM
# 自定义域名: $domain
address=/$domain/$ip
EOFCUSTOM
  echo -e "${GREEN}自定义域名 $domain 解锁已配置${NC}"
}

# 应用配置
apply_config() {
  echo -e "${BLUE}应用配置并重启服务...${NC}"
  
  # 配置系统DNS
  cat > /etc/resolv.conf << EOFDNS
# Generated by dns-unlocker.sh
nameserver 127.0.0.1
EOFDNS

  # 重启服务
  systemctl restart dnsmasq
  if systemctl is-active --quiet dnsmasq; then
    echo -e "${GREEN}DNS解锁设置完成，dnsmasq服务已成功启动${NC}"
  else
    echo -e "${RED}警告: dnsmasq服务启动失败，请检查配置${NC}"
    journalctl -u dnsmasq -n 10
  fi
}

# 显示状态
show_status() {
  echo -e "${BLUE}当前DNS解锁状态:${NC}"
  echo -e "${CYAN}-------------------------${NC}"
  
  # 检查dnsmasq是否运行
  if systemctl is-active --quiet dnsmasq; then
    echo -e "${GREEN}dnsmasq 服务状态: 运行中${NC}"
  else
    echo -e "${RED}dnsmasq 服务状态: 未运行${NC}"
  fi
  
  # 列出已配置的解锁服务
  echo -e "${YELLOW}已配置的解锁服务:${NC}"
  for conf in /etc/dnsmasq.d/*.conf; do
    if [ -f "$conf" ]; then
      service=$(basename "$conf" .conf)
      echo "- $service"
    fi
  done
  
  echo -e "${CYAN}-------------------------${NC}"
}

# 重置配置
reset_config() {
  echo -e "${CYAN}===== 重置所有配置 =====${NC}"
  read -p "确定要重置所有配置吗? (y/n): " confirm
  if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
    # 恢复原始配置
    if [ -f "/etc/dnsmasq.conf.bak" ]; then
      cp /etc/dnsmasq.conf.bak /etc/dnsmasq.conf
    fi
    
    # 清除解锁服务的配置文件
    rm -f /etc/dnsmasq.d/*.conf
    
    # 重启dnsmasq
    systemctl restart dnsmasq
    
    echo -e "${GREEN}已重置所有DNS解锁配置${NC}"
  fi
}

# 主菜单
main_menu() {
  while true; do
    clear
    echo -e "${CYAN}==== DNS解锁脚本 v1.1 ====${NC}"
    echo -e "${YELLOW}1. 解锁Netflix${NC}"
    echo -e "${YELLOW}2. 解锁Disney+${NC}"
    echo -e "${YELLOW}3. 解锁TikTok${NC}"
    echo -e "${YELLOW}4. 解锁AI服务 (OpenAI/Claude/Gemini)${NC}"
    echo -e "${YELLOW}5. 添加自定义域名解锁${NC}"
    echo -e "${YELLOW}6. 应用配置并重启服务${NC}"
    echo -e "${YELLOW}7. 显示当前解锁状态${NC}"
    echo -e "${YELLOW}8. 重置所有配置${NC}"
    echo -e "${YELLOW}0. 退出${NC}"
    echo -e "${CYAN}=======================${NC}"
    read -p "请选择操作: " choice
    
    case $choice in
      1) setup_netflix ;;
      2) setup_disney ;;
      3) setup_tiktok ;;
      4) setup_ai ;;
      5) setup_custom ;;
      6) apply_config ;;
      7) 
         show_status
         read -p "按回车键继续..." dummy
         ;;
      8) reset_config ;;
      0) 
         echo -e "${GREEN}感谢使用DNS解锁脚本!${NC}"
         exit 0
         ;;
      *) 
         echo -e "${RED}无效的选择${NC}"
         sleep 2
         ;;
    esac
  done
}

# 主程序
echo -e "${CYAN}======================================${NC}"
echo -e "${CYAN}        DNS解锁脚本安装向导         ${NC}"
echo -e "${CYAN}======================================${NC}"

# 备份dnsmasq配置
if [ ! -f "/etc/dnsmasq.conf.bak" ] && [ -f "/etc/dnsmasq.conf" ]; then
  cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak
fi

# 设置基本dnsmasq配置
setup_dnsmasq

# 显示主菜单
main_menu
INNEREOF
  chmod +x "$SCRIPT_PATH"
  echo -e "${GREEN}脚本已保存到 $SCRIPT_PATH${NC}"
  echo -e "${YELLOW}请使用以下命令执行脚本:${NC}"
  echo -e "${CYAN}sudo bash $SCRIPT_PATH${NC}"
  exit 0
fi

# 以下是正常的交互模式代码
# 检查root权限
if [ "$(id -u)" != "0" ]; then
   echo -e "${RED}错误: 需要root权限${NC}" 1>&2
   echo -e "${YELLOW}请使用 sudo bash $0 运行此脚本${NC}"
   exit 1
fi

# 安装必要软件
echo -e "${BLUE}正在检查并安装必要软件...${NC}"
apt-get update
apt-get install -y dnsmasq jq

# 配置dnsmasq
setup_dnsmasq() {
  echo -e "${BLUE}配置基本dnsmasq设置...${NC}"
  cat > /etc/dnsmasq.conf << EOFCONF
# 基础配置
cache-size=1024
no-resolv
server=8.8.8.8
server=8.8.4.4
listen-address=127.0.0.1
conf-dir=/etc/dnsmasq.d/,*.conf
EOFCONF

  # 创建目录
  mkdir -p /etc/dnsmasq.d/
  echo -e "${GREEN}dnsmasq基础配置完成${NC}"
}

# 配置Netflix
setup_netflix() {
  echo -e "${CYAN}===== 解锁Netflix =====${NC}"
  read -p "输入用于解锁Netflix的IP: " ip
  if [ -z "$ip" ]; then
    echo -e "${RED}错误: IP地址不能为空${NC}"
    return
  fi
  
  cat > /etc/dnsmasq.d/netflix.conf << EOFSTREAM
# Netflix
address=/netflix.com/$ip
address=/nflxext.com/$ip
address=/nflximg.com/$ip
address=/nflximg.net/$ip
address=/nflxvideo.net/$ip
address=/nflxso.net/$ip
address=/netflix.net/$ip
EOFSTREAM
  echo -e "${GREEN}Netflix解锁已配置${NC}"
}

# 配置Disney+
setup_disney() {
  echo -e "${CYAN}===== 解锁Disney+ =====${NC}"
  read -p "输入用于解锁Disney+的IP: " ip
  if [ -z "$ip" ]; then
    echo -e "${RED}错误: IP地址不能为空${NC}"
    return
  fi
  
  cat > /etc/dnsmasq.d/disney.conf << EOFSTREAM
# Disney+
address=/disney.com/$ip
address=/disney-plus.net/$ip
address=/dssott.com/$ip
address=/disneyplus.com/$ip
address=/bamgrid.com/$ip
address=/disney-portal.my.onetrust.com/$ip
address=/disneystreaming.com/$ip
address=/disney.demdex.net/$ip
address=/disney.my.sentry.io/$ip
address=/cdn.registerdisney.go.com/$ip
address=/global.edge.bamgrid.com/$ip
address=/dssott.com.akamaized.net/$ip
address=/d9.flashtalking.com/$ip
address=/cdn.cdn.unid.go.com/$ip
address=/cws.conviva.com/$ip
EOFSTREAM
  echo -e "${GREEN}Disney+解锁已配置${NC}"
}

# 配置TikTok
setup_tiktok() {
  echo -e "${CYAN}===== 解锁TikTok =====${NC}"
  read -p "输入用于解锁TikTok的IP: " ip
  if [ -z "$ip" ]; then
    echo -e "${RED}错误: IP地址不能为空${NC}"
    return
  fi
  
  cat > /etc/dnsmasq.d/tiktok.conf << EOFSTREAM
# TikTok
address=/tiktok.com/$ip
address=/tiktokv.com/$ip
address=/tiktokcdn.com/$ip
address=/tiktokcdn-us.com/$ip
address=/tik-tokapi.com/$ip
address=/muscdn.com/$ip
EOFSTREAM
  echo -e "${GREEN}TikTok解锁已配置${NC}"
}

# 配置AI服务
setup_ai() {
  echo -e "${CYAN}===== 解锁AI服务 =====${NC}"
  read -p "输入用于解锁AI服务(OpenAI/Claude/Gemini)的IP: " ip
  if [ -z "$ip" ]; then
    echo -e "${RED}错误: IP地址不能为空${NC}"
    return
  fi
  
  cat > /etc/dnsmasq.d/ai.conf << EOFAI
# OpenAI
address=/openai.com/$ip
address=/ai.com/$ip
address=/chat.openai.com/$ip
address=/api.openai.com/$ip
address=/platform.openai.com/$ip

# Claude
address=/anthropic.com/$ip
address=/claude.ai/$ip
address=/api.anthropic.com/$ip

# Gemini
address=/gemini.google.com/$ip
address=/bard.google.com/$ip
address=/generativelanguage.googleapis.com/$ip
EOFAI
  echo -e "${GREEN}AI服务解锁已配置${NC}"
}

# 添加自定义域名
setup_custom() {
  echo -e "${CYAN}===== 添加自定义域名解锁 =====${NC}"
  read -p "输入要解锁的自定义域名: " domain
  if [ -z "$domain" ]; then
    echo -e "${RED}错误: 域名不能为空${NC}"
    return
  fi
  
  read -p "输入用于解锁 $domain 的IP: " ip
  if [ -z "$ip" ]; then
    echo -e "${RED}错误: IP地址不能为空${NC}"
    return
  fi
  
  # 处理域名，去掉可能的http://或https://前缀
  domain=$(echo $domain | sed -e 's|^https\?://||')
  # 移除末尾可能的斜杠
  domain=${domain%/}
  
  cat > "/etc/dnsmasq.d/custom_${domain//./\_}.conf" << EOFCUSTOM
# 自定义域名: $domain
address=/$domain/$ip
EOFCUSTOM
  echo -e "${GREEN}自定义域名 $domain 解锁已配置${NC}"
}

# 应用配置
apply_config() {
  echo -e "${BLUE}应用配置并重启服务...${NC}"
  
  # 配置系统DNS
  cat > /etc/resolv.conf << EOFDNS
# Generated by dns-unlocker.sh
nameserver 127.0.0.1
EOFDNS

  # 重启服务
  systemctl restart dnsmasq
  if systemctl is-active --quiet dnsmasq; then
    echo -e "${GREEN}DNS解锁设置完成，dnsmasq服务已成功启动${NC}"
  else
    echo -e "${RED}警告: dnsmasq服务启动失败，请检查配置${NC}"
    journalctl -u dnsmasq -n 10
  fi
}

# 显示状态
show_status() {
  echo -e "${BLUE}当前DNS解锁状态:${NC}"
  echo -e "${CYAN}-------------------------${NC}"
  
  # 检查dnsmasq是否运行
  if systemctl is-active --quiet dnsmasq; then
    echo -e "${GREEN}dnsmasq 服务状态: 运行中${NC}"
  else
    echo -e "${RED}dnsmasq 服务状态: 未运行${NC}"
  fi
  
  # 列出已配置的解锁服务
  echo -e "${YELLOW}已配置的解锁服务:${NC}"
  for conf in /etc/dnsmasq.d/*.conf; do
    if [ -f "$conf" ]; then
      service=$(basename "$conf" .conf)
      echo "- $service"
    fi
  done
  
  echo -e "${CYAN}-------------------------${NC}"
}

# 重置配置
reset_config() {
  echo -e "${CYAN}===== 重置所有配置 =====${NC}"
  read -p "确定要重置所有配置吗? (y/n): " confirm
  if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
    # 恢复原始配置
    if [ -f "/etc/dnsmasq.conf.bak" ]; then
      cp /etc/dnsmasq.conf.bak /etc/dnsmasq.conf
    fi
    
    # 清除解锁服务的配置文件
    rm -f /etc/dnsmasq.d/*.conf
    
    # 重启dnsmasq
    systemctl restart dnsmasq
    
    echo -e "${GREEN}已重置所有DNS解锁配置${NC}"
  fi
}

# 主菜单
main_menu() {
  while true; do
    clear
    echo -e "${CYAN}==== DNS解锁脚本 v1.1 ====${NC}"
    echo -e "${YELLOW}1. 解锁Netflix${NC}"
    echo -e "${YELLOW}2. 解锁Disney+${NC}"
    echo -e "${YELLOW}3. 解锁TikTok${NC}"
    echo -e "${YELLOW}4. 解锁AI服务 (OpenAI/Claude/Gemini)${NC}"
    echo -e "${YELLOW}5. 添加自定义域名解锁${NC}"
    echo -e "${YELLOW}6. 应用配置并重启服务${NC}"
    echo -e "${YELLOW}7. 显示当前解锁状态${NC}"
    echo -e "${YELLOW}8. 重置所有配置${NC}"
    echo -e "${YELLOW}0. 退出${NC}"
    echo -e "${CYAN}=======================${NC}"
    read -p "请选择操作: " choice
    
    case $choice in
      1) setup_netflix ;;
      2) setup_disney ;;
      3) setup_tiktok ;;
      4) setup_ai ;;
      5) setup_custom ;;
      6) apply_config ;;
      7) 
         show_status
         read -p "按回车键继续..." dummy
         ;;
      8) reset_config ;;
      0) 
         echo -e "${GREEN}感谢使用DNS解锁脚本!${NC}"
         exit 0
         ;;
      *) 
         echo -e "${RED}无效的选择${NC}"
         sleep 2
         ;;
    esac
  done
}

# 主程序
echo -e "${CYAN}======================================${NC}"
echo -e "${CYAN}        DNS解锁脚本安装向导         ${NC}"
echo -e "${CYAN}======================================${NC}"

# 备份dnsmasq配置
if [ ! -f "/etc/dnsmasq.conf.bak" ] && [ -f "/etc/dnsmasq.conf" ]; then
  cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bak
fi

# 设置基本dnsmasq配置
setup_dnsmasq

# 显示主菜单
main_menu
EOF

chmod +x dns-unlocker.sh
