cat > dns-unlocker.sh << 'EOF'
#!/bin/bash
# 简化版DNS解锁脚本

# 检查root权限
if [ "$(id -u)" != "0" ]; then
   echo "错误: 需要root权限" 1>&2
   exit 1
fi

# 安装必要软件
apt-get update
apt-get install -y dnsmasq jq

# 配置dnsmasq
cat > /etc/dnsmasq.conf << EOFCONF
# 基础配置
cache-size=1024
no-resolv
server=8.8.8.8
server=8.8.4.4
listen-address=127.0.0.1
conf-dir=/etc/dnsmasq.d/,*.conf
EOFCONF

# 创建目录
mkdir -p /etc/dnsmasq.d/

# 配置DNS解锁
echo "==== DNS解锁脚本 ===="
echo "1. Netflix/Disney+/TikTok"
echo "2. OpenAI/Claude/Gemini"
read -p "选择要解锁的服务类型: " service_type
read -p "输入解锁IP: " ip

if [ "$service_type" = "1" ]; then
  # 流媒体服务
  cat > /etc/dnsmasq.d/streaming.conf << EOFSTREAM
# Netflix
address=/netflix.com/$ip
address=/nflxext.com/$ip
address=/nflximg.com/$ip
address=/nflximg.net/$ip
address=/nflxvideo.net/$ip
address=/nflxso.net/$ip

# Disney+
address=/disney.com/$ip
address=/disney-plus.net/$ip
address=/dssott.com/$ip
address=/disneyplus.com/$ip
address=/bamgrid.com/$ip
address=/disney-portal.my.onetrust.com/$ip
address=/disneystreaming.com/$ip
address=/disney.demdex.net/$ip
address=/disney.my.sentry.io/$ip
address=/cdn.registerdisney.go.com/$ip
address=/global.edge.bamgrid.com/$ip
address=/dssott.com.akamaized.net/$ip
address=/d9.flashtalking.com/$ip
address=/cdn.cdn.unid.go.com/$ip
address=/cws.conviva.com/$ip

# TikTok
address=/tiktok.com/$ip
address=/tiktokv.com/$ip
address=/tiktokcdn.com/$ip
address=/tiktokcdn-us.com/$ip
address=/tik-tokapi.com/$ip
address=/muscdn.com/$ip
EOFSTREAM
  echo "流媒体服务解锁已配置"
  
elif [ "$service_type" = "2" ]; then
  # AI服务
  cat > /etc/dnsmasq.d/ai.conf << EOFAI
# OpenAI
address=/openai.com/$ip
address=/ai.com/$ip
address=/chat.openai.com/$ip
address=/api.openai.com/$ip
address=/platform.openai.com/$ip

# Claude
address=/anthropic.com/$ip
address=/claude.ai/$ip
address=/api.anthropic.com/$ip

# Gemini
address=/gemini.google.com/$ip
address=/bard.google.com/$ip
address=/generativelanguage.googleapis.com/$ip
EOFAI
  echo "AI服务解锁已配置"
fi

# 配置系统DNS
cat > /etc/resolv.conf << EOFDNS
# Generated by dns-unlocker.sh
nameserver 127.0.0.1
EOFDNS

# 重启服务
systemctl restart dnsmasq
if systemctl is-active --quiet dnsmasq; then
  echo "DNS解锁设置完成，dnsmasq服务已成功启动"
else
  echo "警告: dnsmasq服务启动失败，请检查配置"
  journalctl -u dnsmasq -n 10
fi
EOF

chmod +x dns-unlocker.sh
